### ISSUE TITLE
Create section of table with github aesthetic

### ISSUE THREAD

**Issue by jmuzsik** [jMuzsik/find-an-issue#10]
The idea you spoke of is a nice one. I think it'd look good to have a section of the row to look like the image you mentioned.

I am thinking for it to be like this: 
![issuetemplatething](https://user-images.githubusercontent.com/29470576/45404106-a2718e00-b62b-11e8-8f2e-86f39b40db13.png)

Though, that is just something rough I made quickly. By all means, make it your own style. Add some flare if you'd like. Also, there is no access to star count or fork count in the data.

To do it notice this function in the `utils.js` file:

```
export function urlFormatter(cell) {
  return (
    <a href={cell.S} className="badge badge-success">
      Issue
    </a>
  );
}
```

Which gets used in the `table.js` file:

```
          <TableHeaderColumn
            ref="Url"
            dataField="Url"
            dataFormat={urlFormatter}
          >
```

So you'd replace the dataFormat prop in the title section with your function: 

```
          <TableHeaderColumn
            isKey={true}
            ref="Title"
            dataField="Title"
            dataFormat={titleFormatter}
          >
```

Look up React Bootstrap Table docs for more info. Also, if you need to edit the styling the main way in which the table is styled is in this selector:

```
tbody tr {
  display: grid;
  grid-area: header;
  grid-template-columns: 27% 22% 15% 16% 10% 10%;
}
```

Feel free to give yourself more space for the column, the 27% is the title section atm. 

Perhaps, if you'd like to change things around more, you can put the search boxes above the table for language and repository so it is not mentioned twice. 

To do this may be quite complicated though. You'd have to either stylistically move the filter out of where it automatically goes (in the header) but I do not think that is an option. Custom filter is also a possibility. Probably the best way would be to somehow have multiple columns with the filtering in the header but only the column you are creating below these columns. So, 3 heading columns with search and a column taking up the entire span below these columns being the one you are creating.

Ok, I'll leave it at this! Let me know if you have any questions. Thanks!

**Comment by LeoBorai** [comment]
Hey @jMuzsik! Thanks for inviting me!
I just think that using this component inside a table is not a great idea, but in order to be able to discuss an approach to use the component Im thinking about creating a branch with a proposal design we can work on in order to find a better way to display the info from the table!

Let me know what do you think!

**Comment by jmuzsik** [comment]
@estebanborai sounds good! So you think it would be better to not do a table? It wouldn't be a ton of work to create something new but it would take sometime. The custom filters would have to be made, etc. 

But, i'm open to anything! The frontend should definitely be improved

**Comment by LeoBorai** [comment]
Hey @jMuzsik ! I have been working on *find-an-issue*, I already did some changes that impact the UI a lot.
The main screen is not done but I already work on how it will look like, I would like to have some feedback from you, In order to keep working in the same project, at the moment I just have some sketch of how it looks like for me, so maybe if we can share some ideas would with graphics would be great in order to have a better understanding of how we want it to be!

Thanks for your time!

**Comment by jmuzsik** [comment]
Hi, thanks so much for all the work! But, I didn't think you wanted to redesign everything. Here are my comments: 

* Can you only focus on the table? I would rather keep the header, logo, and hero as is. Sorry you spent all that time making those components.

* Also, I'd rather keep the css, etc. very simple. So, not too much pure css, but more utilisation of bootstrap to make sure it is mobile responsive. And mobile first ideally.

* I like how the issues look, if you focus on that, that would be cool. Though, there is a ton of work that needs to be done. 
  * For example, the colour idea, we'd have to filter out all the languages that are used, and make sure each get the corresponding colour, not only the three or so you use now. In this regard be sure to use the spelling of the languages in the array that the data exists in. Do a filter function to get all the language names that exist in the array or something along those lines.
  * Another example, pagination would need to be created. 
  * Also, dynamic displaying of data. 
  * All of the filtering functions would need to be created, and the state would need to be properly passed to the component that displays the issues.

But, if we start with simply the boxes being right, all else can come together moderately easy. Simply the same pattern that already exists has to be used.

* Also, no need for top languages or top repositories (there is no way to figure out top repositories either way, it would need to be hardcoded). 

* Simply form fields that allow the user to filter based upon parameters. Specifically the filters that already exist, but they would have to be reimplemented, custom filters rather then the `react-bootstrap-table` library doing this for us.

Hope that makes sense and that it is not too much of a downer to read. Let me know what you think, and if you have any questions, but let's please talk first prior to writing code so we have a clear path to take.
