### ISSUE TITLE
react-bootstrap-table is deprecated

### ISSUE THREAD

**Issue by pritam-patil** [jMuzsik/find-an-issue#14]
**react-bootstrap-table** is _deprecated_ as per [their homepage](http://allenfang.github.io/react-bootstrap-table/index.html),  instead react-bootstrap-table2 should be used.

**Comment by jmuzsik** [comment]
Thanks for letting me know Pritam, i'll look into it soon as i can. If you want to try switching to react-bootstrap-table2, by all means give it a go!

**Comment by pritam-patil** [comment]
@jMuzsik - FYI, I have a tested component ready to replace the deprecated `react-bootstrap-table`.
Please let me know how would you like these changes added.
There are couple of ways -

1. Add a **separate Table component** for Newly added table (_using react-bootstrap-table-next_) and **keep a FLAG**  to switch between old and new tables as and if required.
-- This will increase the bundle size (`react-bootstrap-table` + packages of `react-bootstrap-table-next` like filter and pagination)

-- OR --

2. Straightforward replacement of `react-bootstrap-table` with `react-bootstrap-table-next` and its dependant packages. Also replacing old table with new table changes.

Thanks.
