### ISSUE TITLE
Case sensitivity in language search

### ISSUE THREAD

**Issue by lamnhh** [jMuzsik/find-an-issue#2]
Could you make the language search case-insensitive? Since I'm too lazy to hold Shift to type JS or HTML :v 

P.S: also, why is HTML written as HTMl with the L being in lowercase? It looks really weird.

**Comment by jmuzsik** [comment]
Hmm... makes sense, it is quite bothersome. It has to be case sensitive in terms of length, etc. though so you can look up `C` rather then `C++` or the like but in terms of the letters it does not need to be.

It'd take a little bit of a performance hit to do lowercase based upon the current implementation as you'd have to call `onFilterChange` every time any filter changes. Check if it is language being altered and do a custom search through the table data, turn each language string into lowercase and turn each string being searched into lowercase, and compare them (filtering out what meets the comparison).

[this link shows the syntax of what needs to be done](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-store-filtering.js#L67)

Or, I can simply make all the language strings lowercase in the first place 🤔. How about that?

You're right about the HTMl thing! It'll be fixed the next time data is refreshed. I had to manually add the languages so spelling problems had to happen from time to time.

**Comment by pritam-patil** [comment]
This can be closed now.
